services:
  flowise:
    ports:
      - 0.0.0.0:3001:3001

  open-webui:
    ports:
      - 0.0.0.0:8080:8080

  n8n:
    ports:
      - 0.0.0.0:5678:5678

  qdrant:
    ports:
      - 0.0.0.0:6333:6333
      - 0.0.0.0:6334:6334

  neo4j:
    ports:
      - 0.0.0.0:7473:7473
      - 0.0.0.0:7474:7474
      - 0.0.0.0:7687:7687

  langfuse-worker:
    ports:
      - 127.0.0.1:3030:3030

  langfuse-web:
    ports:
      - 0.0.0.0:3000:3000

  clickhouse:
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9009:9009

  minio:
    ports:
      - 127.0.0.1:9010:9000
      - 127.0.0.1:9011:9001

  postgres:
    ports:
      - 127.0.0.1:5433:5432                

  redis:
    ports:
      - 127.0.0.1:6379:6379

  searxng:
    ports:
      - 0.0.0.0:8081:8080

  ollama-cpu:
    ports:
      - 0.0.0.0:11434:11434

  ollama-gpu:
    ports:
      - 0.0.0.0:11434:11434
      
  ollama-gpu-amd:
    ports:
      - 0.0.0.0:11434:11434
